title: Scith
author: Any Nom
name: any-nom
email: anonynomsly@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  I am intrigued by two fundamental questions of intelligence. First, how brain solve seemingly general intelligence problems across variety of species and what constraints does brain structure impose on cognitive abilities. 
  Second, evolution of artificial neural networks and different algorithms to make them learn and perform a variety of tasks needs a general theory by which these network learn and perform different cognitive tasks 
  such as natural language understanding, sensory-motor transformation tasks etc.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: devto,          user_url: "https://dev.to/jekyll" }
    - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
    - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
    - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github,         user_url: "https://github.com/jekyll/minima" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
    - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
    - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
    - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
    - { platform: telegram,       user_url: "https://t.me/jekyll" }
    - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
    - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
